/* games/uno/index.js — UNO: css + game manifest. Registers global.Games['uno']. */
(function (global) {
  'use strict';

  const L = global.PARLOR['uno'].logic;
  const V = global.PARLOR['uno'].view;
  const { newState, currentSide, legalMoves, applyMove, outcome, viewFor, aiMove, describeMove } = L;
  const { render, renderInfo } = V;

  const css = [
    '.uno-wrap{display:flex;flex-direction:column;gap:14px;width:min(100%,640px);margin:0 auto}',
    '.uno-table{width:min(100%,640px);aspect-ratio:640/430;container-type:inline-size;margin:0 auto;border-radius:4.0625cqw;position:relative;overflow:visible;background:radial-gradient(120% 140% at 50% 0%, #2b2622 0%, #211d1a 55%, #181512 100%);border:1px solid #c9c2ae;box-shadow:var(--shadow-md)}',
    '.uno-felt{position:absolute;left:12%;right:12%;top:13%;bottom:13%;border-radius:50%;background:radial-gradient(58% 46% at 50% 50%, rgba(255,236,214,.16), rgba(255,236,214,0) 70%), radial-gradient(120% 130% at 50% 22%, #b04a38 0%, #a34433 52%, #6f2718 100%);border:1.40625cqw solid #5e4327;box-shadow:0 8px 22px rgba(0,0,0,.35), inset 0 0 30px rgba(0,0,0,.4), inset 0 2px 6px rgba(255,255,255,.08)}',
    '.uno-pos{position:absolute;z-index:5;display:flex;justify-content:center;transform:translateY(-50%)}',
    '.uno-pos0{left:50%;bottom:0;top:auto;margin-left:-11.5625cqw;width:23.125cqw;transform:none}',
    '.uno-pos1{left:0;top:50%;width:23.4375cqw}',
    '.uno-pos2{left:50%;top:0;margin-left:-11.5625cqw;width:23.125cqw;transform:none}',
    '.uno-pos3{right:0;top:50%;width:23.4375cqw}',
    '.trio .uno-pos1{left:4%;top:10%;width:23.125cqw;transform:none}',
    '.trio .uno-pos2{left:auto;right:4%;top:10%;width:23.125cqw;margin-left:0;transform:none}',
    '.uno-oppcell{position:relative;display:flex;flex-direction:column;align-items:center;gap:0.9375cqw;padding:1.25cqw 2.1875cqw;border-radius:2.1875cqw;background:var(--surface);border:1px solid var(--hair-strong);box-shadow:0 3px 10px rgba(0,0,0,.35)}',
    '.uno-pos.uno-oppcell{position:absolute}',
    '.uno-oppcell.active{border-color:#ffd97a;animation:uno-turn-glow 1.6s ease-in-out infinite}',
    '@keyframes uno-turn-glow{0%,100%{box-shadow:0 3px 10px rgba(0,0,0,.35), 0 0 0 0 rgba(255,217,122,0)}50%{box-shadow:0 3px 10px rgba(0,0,0,.35), 0 0 0 7px rgba(255,217,122,.25)}}',
    '.uno-oppcell.one{border-color:var(--gold);background:var(--gold-soft);box-shadow:inset 0 0 0 1px var(--gold)}',
    '.uno-one{position:absolute;top:-1.09375cqw;right:-1.09375cqw;width:3.125cqw;height:3.125cqw;border-radius:50%;background:var(--gold);color:#fff;font-family:var(--font-display);font-size:max(8px,1.71875cqw);font-weight:700;display:flex;align-items:center;justify-content:center;box-shadow:0 1px 4px rgba(28,33,30,.3);animation:pill-pulse .9s ease-in-out infinite}',
    '.uno-one.pop{animation:uno-badge-pop .45s var(--ease-spring) both, pill-pulse .9s ease-in-out .55s infinite}',
    '@keyframes uno-badge-pop{0%{transform:scale(0)}60%{transform:scale(1.45)}100%{transform:scale(1)}}',
    '.uno-burst{position:absolute;top:-2.5cqw;left:50%;z-index:9;font-family:var(--font-display);font-weight:900;font-size:max(13px,3.4375cqw);color:#a34433;letter-spacing:.05em;text-shadow:0 1px 3px rgba(28,33,30,.35);pointer-events:none;transform:translateX(-50%);animation:uno-burst .9s var(--ease-spring) both}',
    '@keyframes uno-burst{0%{opacity:0;transform:translateX(-50%) scale(.3) rotate(-14deg)}35%{opacity:1;transform:translateX(-50%) scale(1.35) rotate(6deg)}60%{opacity:1;transform:translateX(-50%) scale(1) rotate(-3deg)}100%{opacity:0;transform:translateX(-50%) scale(1.05) rotate(0)}}',
    '.uno-suitbeat{display:inline-block;animation:uno-suitbeat .5s var(--ease-spring) both}',
    '@keyframes uno-suitbeat{0%{transform:scale(1.6);filter:brightness(1.5)}100%{transform:scale(1);filter:brightness(1)}}',
    '.uno-dir.dirbeat{animation:dir-spin 9s linear infinite, uno-dirbeat .55s var(--ease-spring)}',
    '.uno-dir.ccw.dirbeat{animation:dir-spin 9s linear infinite reverse, uno-dirbeat .55s var(--ease-spring)}',
    '@keyframes uno-dirbeat{from{transform:rotate(360deg)}to{transform:rotate(0)}}',
    '.uno-oppname{font-size:max(10px,1.875cqw);font-weight:600;color:#5c6560;letter-spacing:.02em}',
    '.uno-backs{display:flex}',
    '.uno-oppcell .uno-backs .uno-card{width:4.375cqw;height:6.25cqw;border-radius:1.09375cqw;margin-left:-1.71875cqw}',
    '.uno-oppcell .uno-backs .uno-card:first-child{margin-left:0}',
    '.uno-mid{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:3;display:flex;flex-direction:column;align-items:center;gap:1.25cqw;max-width:92%}',
    '.uno-piles{display:flex;align-items:center;justify-content:center;gap:4.0625cqw}',
    '.uno-pile{position:relative;perspective:420px}',
    '.uno-pile.still .uno-card{animation:none}',
    '.uno-deck{display:grid;place-items:center;width:8.75cqw;height:12.5cqw}',
    '.uno-deck .uno-card{grid-area:1/1}',
    '.uno-d1{transform:translate(-6px,-7px) rotate(-6deg);opacity:.4}',
    '.uno-d2{transform:translate(-3px,-3px) rotate(-3deg);opacity:.7}',
    '.uno-d3{z-index:1}',
    '.uno-deck.shuffling{animation:dir-spin .8s var(--ease-out) both}',
    '.uno-deck.dealt .uno-d3{animation:deck-pop .35s var(--ease-spring) both}',
    '.uno-disc{display:grid;place-items:center;width:9.6875cqw;height:13.4375cqw}',
    '.uno-disc .uno-card{grid-area:1/1}',
    '.uno-under{transform:translate(-4px,-5px) rotate(-5deg);opacity:.75;animation:none}',
    '.uno-disc .uno-card:not(.uno-under){z-index:1}',
    '.uno-note{position:absolute;top:-3.75cqw;left:50%;transform:translateX(-50%);white-space:nowrap;font-size:max(10px,1.875cqw);font-weight:700;letter-spacing:.02em;color:#f7f2e5;background:#232836;padding:0.46875cqw 1.71875cqw;border-radius:999px;box-shadow:0 2px 6px rgba(28,33,30,.3);pointer-events:none;z-index:6;animation:note-fade 1.6s var(--ease-out) both}',
    '.uno-pos.still .uno-card{animation:none}',
    '.uno-hand.still .uno-card{animation:none}',
    '.uno-disc .uno-card.topin{animation:uno-topin .18s ease both}',
    '.uno-disc .uno-card.topin.late{animation-delay:.34s}',
    '@keyframes uno-topin{from{opacity:0;transform:scale(.86)}to{opacity:1;transform:none}}',
    '.uno-pile .cnt{position:absolute;bottom:-1.25cqw;right:-1.25cqw;font-size:max(9px,1.796875cqw);font-weight:700;background:#fff;border:1px solid #d3cdbd;border-radius:999px;padding:0.15625cqw 1.25cqw;color:#47514b;box-shadow:0 1px 3px rgba(28,33,30,.12)}',
    '.uno-info{font-size:max(10px,2.03125cqw);line-height:1.5;color:#47514b}',
    '.uno-dirrow{display:flex;align-items:center;gap:0.9375cqw}',
    '.uno-sep{opacity:.45}',
    '.uno-dir{display:inline-block;font-size:max(10px,2.34375cqw);line-height:1;animation:dir-spin 9s linear infinite}',
    '.uno-dir.ccw{animation-direction:reverse}',
    '.uno-suit-r{color:#a34433;font-weight:700}.uno-suit-y{color:#a87c15;font-weight:700}.uno-suit-g{color:#1e5634;font-weight:700}.uno-suit-b{color:#2e4d74;font-weight:700}',
    '.uno-hand{position:relative;display:flex;flex-wrap:wrap;justify-content:center;align-items:flex-end;min-height:92px;padding-top:16px}',
    '.uno-hand .uno-card{margin-left:-16px}',
    '.uno-hand .uno-card:first-child{margin-left:0}',
    '.uno-still{animation:none !important}',
    '.uno-card{position:relative;touch-action:manipulation;width:52px;height:74px;border-radius:11px;display:flex;align-items:center;justify-content:center;background:#20242e;box-shadow:0 3px 8px rgba(28,33,30,.28);flex:0 0 auto;transform:rotate(var(--rot,0deg)) translateY(calc(var(--lift,0px) * -1));animation:uno-deal .3s var(--ease-out) both;transition:transform .32s var(--ease-glide)}',
    '.uno-flycard{animation:none;width:44px;height:64px;position:absolute;left:0;top:0;z-index:60;pointer-events:none;box-shadow:0 4px 10px rgba(28,33,30,.4)}',
    '.uno-card::before{content:"";position:absolute;inset:0;border-radius:11px;box-shadow:inset 0 1px 0 rgba(255,255,255,.35),inset 0 -3px 8px rgba(0,0,0,.28);pointer-events:none}',
    '.uno-oval{position:absolute;inset:19% 7%;background:#f7f2e5;border-radius:50%;transform:rotate(-16deg);box-shadow:inset 0 0 0 1.5px rgba(28,33,30,.14)}',
    '.uno-val{position:relative;z-index:1;font-family:var(--font-display);font-weight:900;font-size:25px;line-height:1;color:#fff;transform:rotate(-16deg);user-select:none}',
    '.uno-idx{position:absolute;z-index:1;top:4px;left:6px;font-family:var(--font-display);font-size:10px;font-weight:800;line-height:1;color:#f7f2e5;text-shadow:0 1px 2px rgba(0,0,0,.55);transform:rotate(-16deg)}',
    '.uno-idx.b{top:auto;left:auto;bottom:4px;right:6px;transform:rotate(164deg)}',
    '.uno-table .uno-val{font-size:3.90625cqw}',
    '.uno-table .uno-idx{font-size:1.5625cqw}',
    '.uno-card.r{background:linear-gradient(140deg,#b04a33,#7f2a1c)}',
    '.uno-card.r .uno-val{color:#9c2f1e}',
    '.uno-card.y{background:linear-gradient(140deg,#d2a12e,#9c7415)}',
    '.uno-card.y .uno-val{color:#8a6510}',
    '.uno-card.g{background:linear-gradient(140deg,#3c8551,#1e5634)}',
    '.uno-card.g .uno-val{color:#1e5634}',
    '.uno-card.b{background:linear-gradient(140deg,#48699a,#2a466e)}',
    '.uno-card.b .uno-val{color:#2a466e}',
    '.uno-card.w{background:conic-gradient(#b04a33 0 25%,#48699a 0 50%,#3c8551 0 75%,#d2a12e 0 100%)}',
    '.uno-card.w .uno-val{color:#232836}',
    '.uno-card.back{background:#232836;width:34px;height:48px}',
    '.uno-card.back .uno-oval{inset:22% 14%;background:#f7f2e5}',
    '.uno-card.back::after{content:"";position:absolute;z-index:1;left:50%;top:50%;width:9px;height:13px;margin:-6.5px 0 0 -4.5px;border-radius:50%;background:#c29330;transform:rotate(-16deg)}',
    '.uno-card.back.uno-under{width:8.125cqw;height:11.5625cqw}',
    '.uno-deck .uno-card.back{width:8.125cqw;height:11.5625cqw}',
    '.uno-backs .uno-card:nth-child(2){animation-delay:.03s}',
    '.uno-backs .uno-card:nth-child(3){animation-delay:.06s}',
    '.uno-backs .uno-card:nth-child(4){animation-delay:.09s}',
    '.uno-backs .uno-card:nth-child(5){animation-delay:.12s}',
    '.uno-backs .uno-card:nth-child(6){animation-delay:.15s}',
    '.uno-backs .uno-card:nth-child(7){animation-delay:.18s}',
    '.uno-hand .uno-card:nth-child(2){animation-delay:.03s}',
    '.uno-hand .uno-card:nth-child(3){animation-delay:.06s}',
    '.uno-hand .uno-card:nth-child(4){animation-delay:.09s}',
    '.uno-hand .uno-card:nth-child(5){animation-delay:.12s}',
    '.uno-hand .uno-card:nth-child(6){animation-delay:.15s}',
    '.uno-hand .uno-card:nth-child(7){animation-delay:.18s}',
    '.uno-hand .uno-card:nth-child(8){animation-delay:.21s}',
    '.uno-hand .uno-card:nth-child(9){animation-delay:.24s}',
    '.uno-hand .uno-card:nth-child(10){animation-delay:.27s}',
    '.uno-hand .uno-card:nth-child(11){animation-delay:.30s}',
    '.uno-hand .uno-card:nth-child(12){animation-delay:.33s}',
    '.uno-card.can{cursor:pointer;outline:3px solid #16683f;outline-offset:1px;transition:transform .14s var(--ease-spring), outline-color .12s, box-shadow .12s}',
    '.uno-card.can:hover{transform:translateY(-16px) scale(1.07) rotate(0);z-index:50}',
    '.uno-card.pend{outline:3px solid #fff;box-shadow:0 0 0 5px rgba(22,104,63,.5), 0 4px 12px rgba(28,33,30,.3);transform:translateY(-16px) scale(1.07) rotate(0);z-index:50}',
    '.uno-card.last{outline:3px solid var(--gold);animation:uno-last-pulse 1.2s ease-in-out infinite}',
    '@keyframes uno-last-pulse{0%,100%{box-shadow:0 2px 6px rgba(28,33,30,.22), 0 0 0 0 rgba(194,147,48,0)}50%{box-shadow:0 2px 6px rgba(28,33,30,.22), 0 0 0 9px rgba(194,147,48,.4)}}',
    '.uno-card.drawn{animation:uno-drawin .45s var(--ease-out) both;animation-delay:.1s}',
    '.uno-actions{display:flex;gap:12px;justify-content:center;flex-wrap:wrap;min-height:38px}',
    '.uno-suitbtn{font-weight:800;border-radius:10px;padding:9px 18px;color:#fff;border:none;cursor:pointer;letter-spacing:.03em;box-shadow:0 3px 0 rgba(0,0,0,.25);transition:transform .1s, box-shadow .1s, filter .15s}',
    '.uno-suitbtn.suitin{animation:entry-in .32s var(--ease-spring) backwards}',
    '.uno-suitbtn:hover{filter:brightness(1.12);transform:translateY(-1px)}',
    '.uno-suitbtn:active{transform:translateY(2px);box-shadow:0 1px 0 rgba(0,0,0,.25)}',
    '.uno-suitbtn-r{background:#7f2a1c}.uno-suitbtn-y{background:#9c7415}.uno-suitbtn-g{background:#1e5634}.uno-suitbtn-b{background:#2a466e}',
    '.uno-hint{color:#8a6a1f;font-weight:600}',
    '@keyframes uno-drawin{0%{opacity:0;transform:translate(-46px,-70px) rotate(-14deg) scale(.7)}100%{opacity:1;transform:rotate(var(--rot,0deg)) translateY(calc(var(--lift,0px) * -1)) scale(1)}}',
    '@keyframes note-fade{0%{opacity:0;transform:translate(-50%,8px)}12%{opacity:1;transform:translate(-50%,0)}72%{opacity:1;transform:translate(-50%,0)}100%{opacity:0;transform:translate(-50%,-10px)}}',
    '@keyframes deck-pop{0%{transform:scale(.8)}60%{transform:scale(1.1)}100%{transform:scale(1)}}',
    '@media (max-width:600px){.uno-wrap{gap:10px}.uno-hand{min-height:84px;padding-top:12px}.uno-hand .uno-card{width:46px;height:66px;margin-left:-14px}.uno-actions{gap:8px;min-height:34px}.uno-suitbtn{padding:8px 14px}}'
  ].join('\n');


  const game = {
    id: 'uno',
    title: 'UNO',
    blurb: 'The classic card game — 2 to 4 players, wilds, +2, skip and reverse.',
    hint: "Play a card matching the top card's color or value — or draw.",
    sideList: ['0', '1', '2', '3'],
    pickSide: false,
    sideName(side) { return 'Player ' + (parseInt(side, 10) + 1); },
    localConfigs() { return [{ kind: 'human' }, { kind: 'bot' }, { kind: 'bot' }, { kind: 'bot' }]; },
    intensity(view, mySide) {
      if (view && Array.isArray(view.counts)) {
        for (let i = 0; i < view.counts.length; i++) {
          if (String(i) !== String(mySide) && view.counts[i] === 1) return 2;
        }
      }
      return 1;
    },
    resultIcon: '<span class="gicon-dots"><i></i><i></i><i></i><i></i></span>',
    resultTone(text, mySide) { const mine = this.sideName(mySide); return text.indexOf(mine + ' wins') >= 0 ? 'win' : 'lose'; },
    css,
    newState,
    currentSide,
    legalMoves,
    applyMove,
    outcome,
    viewFor,
    aiMove,
    describeMove,
    render,
    renderInfo
  };


  global.Games = global.Games || {};
  global.Games['uno'] = game;
  if (typeof module !== 'undefined' && module.exports) module.exports = game;
})(typeof window !== 'undefined' ? window : globalThis);
